[package]
name = "lobs"
version = "0.1.0"
edition = "2021"

[dependencies]
binance = "0.21.0"
chrono = "0.4.39"
serde = "1.0.216"
serde_json = "1.0.134"
tokio = {version = "1.42.0", features = ["full"] }
